OUTDIR : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/hrnet_ppm_focus'
N_EPOCH : 70
MAX_ITER : 100000
TRAIN_FOCUS : 0
RESUME : -1
PRETRAINED : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/hrnet_w48_cityscapes_cls19_1024x2048_ohem_trainvalset.pth'
# ---------------------------------------------------------
DATASET:
# ---------------------------------------------------------
  TRAIN        : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/train'
  VAL          : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/val'
  N_CLASS      : 11
  BATCHSIZE    : 4
  IMGSIZE      : (512, 512)
  AUGMENTATION : []

# ---------------------------------------------------------
MODEL:
# ---------------------------------------------------------
  BACKBONE                   : 'HRNet'
  GLOBAL_DECODER             : 'PPM'
  FOCUS_DECODER              : True
  FPN                        : False
  N_CLASS                    : 11
  PPM_IN                     : 720
  # The output channel of backbone
  FC_DIM                     : [720]
  # The adaptive pooling scale of Payramid Pooling Module
  POOL_SCALES                : (1, 2, 3, 6)
  SEGSIZE                    : (512, 512)
  EROSION_DILATION_KERNAL    : 11

# ---------------------------------------------------------
LOSS:
# ---------------------------------------------------------
  TYPE            : 'CrossEntropy'
  IGNORE_INDEX    : -1
  LOSS_WEIGHT     : (1, 1)
  CLASS_WEIGHT    : None
  # The threshold probability in OHEM loss, a pixel will be use when probability less than THRESHOLD
  THRESHOLD       : 0.7
  # minimum number of pixel using in OHEM loss
  MIN_KEPT        : 100000

# ---------------------------------------------------------
OPTIMIZER:
# ---------------------------------------------------------
  TYPE           : 'SGD'
  LR             : 0.0001
  BETA1          : 0.9
  BETA2          : 0.999
  WEIGHT_DECAY   : 1e-5
  LR_SCHEDULER   : 'poly'

# ---------------------------------------------------------
TEST:
# ---------------------------------------------------------
  TESTIMAGE       : '/media/xiehaofeng/新加卷/things/EvLab-SSBenchmark/val/38.tif'
  CHECKPOINT      : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/hrnet_ppm_focus/checkpoints2/67epoch.pth'
  PATCHSIZE       : 1024
  OVERLAP         : 0.5
  OUTDIR          : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/38.tif'