OUTDIR : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/resnet_GAN_focus'
N_EPOCH : 200
MAX_ITER : 1000000
TRAIN_FOCUS : 0
RESUME : -1
PRETRAINED : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/pretrained/resnet50-19c8e357.pth'
# ---------------------------------------------------------
DATASET:
# ---------------------------------------------------------
  TRAIN        : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/train'
  VAL          : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/val'
  N_CLASS      : 11
  BATCHSIZE    : 4
  IMGSIZE      : (512, 512)
  AUGMENTATION : []

# ---------------------------------------------------------
MODEL:
# ---------------------------------------------------------
  BACKBONE                   : 'resnet50'
  GLOBAL_DECODER             : 'PPM'
  FOCUS_DECODER              : False
  FPN                        : True
  N_CLASS                    : 11
  PPM_IN                     : 1024
  # The output channel of backbone
  FC_DIM                     : (256, 512, 1024, 2048)
  # The adaptive pooling scale of Payramid Pooling Module
  POOL_SCALES                : (1, 2, 3, 6)
  SEGSIZE                    : (512, 512)
  EROSION_DILATION_KERNAL    : 11

# ---------------------------------------------------------
LOSS:
# ---------------------------------------------------------
  TYPE            : 'CrossEntropy'
  IGNORE_INDEX    : -1
  LOSS_WEIGHT     : (1, 1)
  CLASS_WEIGHT    : None
  # The threshold probability in OHEM loss, a pixel will be use when probability less than THRESHOLD
  THRESHOLD       : 0.7
  # minimum number of pixel using in OHEM loss
  MIN_KEPT        : 100000

# ---------------------------------------------------------
OPTIMIZER:
# ---------------------------------------------------------
  TYPE           : 'Adam'
  LR             : 0.0001
  BETA1          : 0.9
  BETA2          : 0.999
  WEIGHT_DECAY   : 1e-5
  LR_SCHEDULER   : ''

# ---------------------------------------------------------
# GAN
# ---------------------------------------------------------
GAN:
  G_LR         : 0.00004
  D_LR         : 0.00001
  THRESHOLD    : 0.85
  LEAKYRELU    : 0.2

# ---------------------------------------------------------
TEST:
# ---------------------------------------------------------
  TESTIMAGE       : '/media/xiehaofeng/新加卷/things/EvLab-SSBenchmark/val/38.tif'
  CHECKPOINT      : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/hrnet_ppm_focus/checkpoints/67epoch.pth'
  PATCHSIZE       : 1024
  OVERLAP         : 0.5
  OUTDIR          : '/media/xiehaofeng/新加卷/things/evlab-benchmark-segfix/trimap2.0/38.tif'